/* ╔══════════════════════════════════════════════════════════════════════════╗
 * ║  HARNESS DESIGNER — modal-summary.js                                       ║
 * ╠══════════════════════════════════════════════════════════════════════════╣
 * ║  Modal de resumen de conexiones y exportación Excel/CSV.                   
 * ║  Secciones: 33, 34                                                         ║
 * ╚══════════════════════════════════════════════════════════════════════════╝
 */

/* ══════════════════════════════════════════════════════════════════════════
 * SECCIÓN 33: MODAL DE RESUMEN
 * Tabla resumen con todas las conexiones del arnés actual, incluyendo
 * columnas de origen, destino, señal, calibre, longitud y color.
 * ══════════════════════════════════════════════════════════════════════════ */
function openSummaryModal(nodeId){
  const node=AppState.nodes[nodeId]; if(!node) return;
  summaryTableBody.innerHTML='';
  const rows=[];
  
  // Helper function to get display name (label if exists, otherwise name)
  function getDisplayName(nodeObj, nodeId) {
    if(nodeObj.label && nodeObj.label.trim()) {
      return nodeObj.label.trim();
    }
    return nodeObj.name || nodeId;
  }
  
  // Show outgoing connections from this node
  (node.mapping||[]).forEach(m=>{ 
    if(m && m.targetConnectorId && m.targetPin && !m.isAutoGenerated) {
      const targetNode = AppState.nodes[m.targetConnectorId];
      rows.push({
        originName:getDisplayName(node, nodeId),
        originPin:m.pin,
        destName:getDisplayName(targetNode, m.targetConnectorId),
        destPin:m.targetPin,
        signal:m.signal||'',
        cableType:m.cableType||'',
        awg:formatAWGMM2(m.awg||''),
        iecColor:m.iecColor||''
      });
    }
  });
  
  // Show incoming connections to this node from other nodes
  Object.keys(AppState.nodes).forEach(otherId=>{
    if(otherId === nodeId) return;
    const otherNode = AppState.nodes[otherId];
    if(!otherNode || !Array.isArray(otherNode.mapping)) return;
    otherNode.mapping.forEach(m=>{
      if(m && m.targetConnectorId === nodeId && m.targetPin && !m.isAutoGenerated) {
        rows.push({
          originName:getDisplayName(otherNode, otherId),
          originPin:m.pin,
          destName:getDisplayName(node, nodeId),
          destPin:m.targetPin,
          signal:m.signal||'',
          cableType:m.cableType||'',
          awg:formatAWGMM2(m.awg||''),
          iecColor:m.iecColor||''
        });
      }
    });
  });

  if(!rows.length){
    const tr=document.createElement('tr'); 
    const td=document.createElement('td'); 
    td.colSpan=8; 
    td.textContent='Sin conexiones definidas.'; 
    td.style.color='var(--muted2)'; 
    td.style.textAlign='center'; 
    td.style.padding='16px'; 
    tr.appendChild(td); 
    summaryTableBody.appendChild(tr);
  } else {
    rows.forEach(r=>{
      const tr=document.createElement('tr'); 
      tr.className='mapping-row';
      [r.originName,r.originPin,r.destName,r.destPin,r.signal,r.cableType,r.awg,r.iecColor].forEach(v=>{ 
        const td=document.createElement('td'); 
        td.textContent=v; 
        tr.appendChild(td); 
      });
      summaryTableBody.appendChild(tr);
    });
  }
  summaryBackdrop.style.display='flex';
}
summaryClose.addEventListener('click',()=>{ summaryBackdrop.style.display='none'; });

exportCsvBtn.addEventListener('click',()=>{
  if(AppState.harness.current>=0) saveCurrentHarnessSnapshot();
  
  // Helper function to get display name (label if exists, otherwise name)
  function getDisplayName(nodeObj, nodeId) {
    if(nodeObj.label && nodeObj.label.trim()) {
      return nodeObj.label.trim();
    }
    return nodeObj.name || nodeId;
  }
  
  const rows=[['Arnes','Conector Origen','Pin Origen','Conector Destino','Pin Destino','Señal','Tipo Cable','AWG/mm2','Color']];
  AppState.harness.list.forEach((h,hi)=>{
    const hname=(h.meta&&h.meta.name)||`Arnés ${hi+1}`;
    const hnodes={};
    (h.nodes||[]).forEach(n=>{ hnodes[n.id]=n; });
    (h.nodes||[]).forEach(n=>{
      (n.mapping||[]).forEach(m=>{
        if(!m.isAutoGenerated && m.targetConnectorId) {
          const targetNode = hnodes[m.targetConnectorId];
          if(targetNode) {
            rows.push([
              hname,
              getDisplayName(n, n.id),
              m.pin||'',
              getDisplayName(targetNode, m.targetConnectorId),
              m.targetPin||'',
              m.signal||'',
              m.cableType||'',
              formatAWGMM2(m.awg||''),
              m.iecColor||''
            ]);
          }
        }
      });
    });
  });
  const csv=rows.map(r=>r.map(c=>`"${String(c||'').replace(/"/g,'""')}"`).join(',')).join('\r\n');
  const blob=new Blob([csv],{type:'text/csv;charset=utf-8;'});
  const url=URL.createObjectURL(blob);
  const a=document.createElement('a'); a.href=url; a.download='harnes_mappings.csv';
  document.body.appendChild(a); a.click();
  setTimeout(()=>{ URL.revokeObjectURL(url); a.remove(); },500);
});

// Función para exportar a Excel con SheetJS (API moderna) - Múltiples hojas y formato profesional
exportExcelBtn.addEventListener('click',()=>{
  if(AppState.harness.current>=0) saveCurrentHarnessSnapshot();
  
  // Helper function to get display name (label if exists, otherwise name)
  function getDisplayName(nodeObj, nodeId) {
    if(nodeObj.label && nodeObj.label.trim()) {
      return nodeObj.label.trim();
    }
    return nodeObj.name || nodeId;
  }
  
    
  // Función para aplicar formato profesional usando ExcelJS (sin bold)
  function applyProfessionalFormat(worksheet, sheetName) {
    // Aplicar formato al título (fila 1)
    const titleRow = worksheet.getRow(1);
    titleRow.eachCell((cell, colNumber) => {
      cell.font = {
        size: 14, // Reducido de 16 a 14
        color: { argb: 'FFFFFFFF' } // Blanco
      };
      cell.fill = {
        type: 'pattern',
        pattern: 'solid',
        fgColor: { argb: 'FF4A90E2' } // Azul más claro y estético
      };
      cell.alignment = {
        horizontal: 'center',
        vertical: 'center',
        wrapText: true
      };
      cell.border = {
        top: { style: 'medium', color: { argb: 'FF2E7DAF' } },
        bottom: { style: 'medium', color: { argb: 'FF2E7DAF' } },
        left: { style: 'medium', color: { argb: 'FF2E7DAF' } },
        right: { style: 'medium', color: { argb: 'FF2E7DAF' } }
      };
    });
    
    // Aplicar formato a las cabeceras de datos (fila 3) - sin bold
    const headerRow = worksheet.getRow(3);
    headerRow.eachCell((cell, colNumber) => {
      cell.font = {
        size: 11, // Reducido de 12 a 11
        color: { argb: 'FFFFFFFF' } // Blanco
      };
      cell.fill = {
        type: 'pattern',
        pattern: 'solid',
        fgColor: { argb: 'FF4A90E2' } // Azul más claro y estético
      };
      cell.alignment = {
        horizontal: 'center',
        vertical: 'center',
        wrapText: true
      };
      cell.border = {
        top: { style: 'medium', color: { argb: 'FF2E7DAF' } },
        bottom: { style: 'medium', color: { argb: 'FF2E7DAF' } },
        left: { style: 'medium', color: { argb: 'FF2E7DAF' } },
        right: { style: 'medium', color: { argb: 'FF2E7DAF' } }
      };
    });
    
    // Aplicar formato a las filas de datos con alternancia (desde fila 4)
    for(let row = 4; row <= 1000; row++) {
      const dataRow = worksheet.getRow(row);
      const isAlternating = row % 2 === 0;
      
      dataRow.eachCell((cell, colNumber) => {
        cell.font = {
          size: 11,
          color: { argb: 'FF1A202C' } // Texto oscuro
        };
        cell.fill = {
          type: 'pattern',
          pattern: 'solid',
          fgColor: { argb: isAlternating ? 'FFF1F5F9' : 'FFFFFFFF' } // Alternancia
        };
        cell.alignment = {
          vertical: 'center',
          wrapText: true
        };
        cell.border = {
          top: { style: 'thin', color: { argb: 'FFCBD5E1' } },
          bottom: { style: 'thin', color: { argb: 'FFCBD5E1' } },
          left: { style: 'thin', color: { argb: 'FFCBD5E1' } },
          right: { style: 'thin', color: { argb: 'FFCBD5E1' } }
        };
      });
    }
    
    // Ajustar ancho de columnas
    worksheet.getColumn(1).width = 18; // Conector Origen
    worksheet.getColumn(2).width = 8;  // Pin Origen
    worksheet.getColumn(3).width = 18; // Conector Destino
    worksheet.getColumn(4).width = 8;  // Pin Destino
    worksheet.getColumn(5).width = 20; // Señal
    worksheet.getColumn(6).width = 18; // Tipo Cable
    worksheet.getColumn(7).width = 6;  // AWG/mm2
    worksheet.getColumn(8).width = 16; // Color
    
    // Congelar la tercera fila (cabeceras de datos)
    worksheet.views = [
      { state: 'frozen', xSplit: 0, ySplit: 3, topLeftCell: 'A4', activeCell: 'A4' }
    ];
  }
  
  // Generar archivo Excel usando ExcelJS
  try {
    const workbook = new ExcelJS.Workbook();
    
    // Generar hoja de resumen con datos del proyecto y estadísticas
    const summarySheet = workbook.addWorksheet('Resumen del Proyecto');
    
    // Calcular estadísticas generales
    let totalNodes = 0;
    let totalProjectConnections = 0;
    let totalConnectors = 0;
    let totalTerminals = 0;
    let totalBifurcations = 0;
    
    AppState.harness.list.forEach(h => {
      if (h.nodes) {
        totalNodes += h.nodes.length;
        h.nodes.forEach(node => {
          if (node.type === 'connector') totalConnectors++;
          else if (node.type === 'terminal') totalTerminals++;
          else if (node.type === 'bifurcation') totalBifurcations++;
          
          if (node.mapping) {
            node.mapping.forEach(m => {
              if (!m.isAutoGenerated && m.targetConnectorId) {
                totalProjectConnections++;
              }
            });
          }
        });
      }
    });
    
    // Agregar todos los datos del proyecto (del modal de datos de proyecto)
    summarySheet.addRow(['DATOS COMPLETOS DEL PROYECTO']);
    summarySheet.addRow(['']);
    summarySheet.addRow(['Business Unit:', AppState.project?.meta?.businessUnit || 'No especificado']);
    summarySheet.addRow(['Nombre del Proyecto:', AppState.project?.meta?.projectName || 'No especificado']);
    summarySheet.addRow(['Contraseña:', AppState.project?.meta?.projectPassword || 'No especificado']);
    summarySheet.addRow(['Responsable de Diseño:', AppState.project?.meta?.designResponsible || 'No especificado']);
    summarySheet.addRow(['Cabecera del Proyecto:', AppState.project?.meta?.projectHeader || 'No especificado']);
    summarySheet.addRow(['Normativa Aplicable:', AppState.project?.meta?.applicableStandard || 'No especificado']);
    summarySheet.addRow(['Requisitos Específicos:', AppState.project?.meta?.specificRequirements || 'No especificado']);
    summarySheet.addRow(['Nombre ICM del Proyecto:', AppState.project?.meta?.icmProjectName || 'No especificado']);
    summarySheet.addRow(['Centro de Trabajo:', AppState.project?.meta?.workCenter || 'No especificado']);
    summarySheet.addRow(['Área ICM:', AppState.project?.meta?.icmArea || 'No especificado']);
    summarySheet.addRow(['Fecha Requerida:', AppState.project?.meta?.requiredDate || 'No especificado']);
    summarySheet.addRow(['Fecha de Generación:', new Date().toLocaleDateString('es-ES')]);
    summarySheet.addRow(['']);
    
        
    // Agregar lista simple de arneses (sin P/N)
    summarySheet.addRow(['LISTADO DE ARNESES']);
    summarySheet.addRow(['']);
    summarySheet.addRow(['Nombre del Arnés']);
    
    AppState.harness.list.forEach((h, index) => {
      const hname = (h.meta && h.meta.name) || `Arnés ${index + 1}`;
      summarySheet.addRow([hname]);
    });
    
    // Aplicar formato a la hoja de resumen simplificada
    function applySummaryFormat(worksheet) {
      // Formato para títulos de sección (sin bold)
      const sectionTitles = [1, 16]; // Filas de títulos actualizadas (sin RESUMEN)
      sectionTitles.forEach(rowNum => {
        const row = worksheet.getRow(rowNum);
        row.eachCell((cell) => {
          cell.font = {
            size: 12,
            color: { argb: 'FFFFFFFF' }
          };
          cell.fill = {
            type: 'pattern',
            pattern: 'solid',
            fgColor: { argb: 'FF4A90E2' }
          };
          cell.alignment = {
            horizontal: 'center',
            vertical: 'center'
          };
        });
      });
      
      // Formato para cabecera de lista de arneses (sin bold)
      const headerRow = worksheet.getRow(18); // Fila de cabecera "Nombre del Arnés" (actualizada)
      headerRow.eachCell((cell) => {
        cell.font = {
          size: 11,
          color: { argb: 'FFFFFFFF' }
        };
        cell.fill = {
          type: 'pattern',
          pattern: 'solid',
          fgColor: { argb: 'FF2E7DAF' }
        };
        cell.alignment = {
          horizontal: 'center',
          vertical: 'center'
        };
        cell.border = {
          top: { style: 'thin', color: { argb: 'FF000000' } },
          bottom: { style: 'thin', color: { argb: 'FF000000' } },
          left: { style: 'thin', color: { argb: 'FF000000' } },
          right: { style: 'thin', color: { argb: 'FF000000' } }
        };
      });
      
      // Formato para datos de arneses
      for(let row = 19; row <= worksheet.rowCount; row++) {
        const dataRow = worksheet.getRow(row);
        dataRow.eachCell((cell) => {
          cell.font = {
            size: 10,
            color: { argb: 'FF1A202C' }
          };
          cell.alignment = {
            vertical: 'center',
            horizontal: 'left'
          };
          cell.border = {
            top: { style: 'thin', color: { argb: 'FFD0D0D0' } },
            bottom: { style: 'thin', color: { argb: 'FFD0D0D0' } },
            left: { style: 'thin', color: { argb: 'FFD0D0D0' } },
            right: { style: 'thin', color: { argb: 'FFD0D0D0' } }
          };
        });
      }
      
      // Ajustar ancho de columnas
      worksheet.getColumn(1).width = 40; // Nombre del arnés (única columna)
      worksheet.getColumn(2).width = 20; // Etiquetas
    }
    
    applySummaryFormat(summarySheet);
    
    // Generar hojas individuales para cada arnés
    let totalHarnessConnections = 0;
    AppState.harness.list.forEach((h, hi) => {
      const hname = (h.meta && h.meta.name) || `Arnés ${hi + 1}`;
      const hnodes = {};
      (h.nodes || []).forEach(n => { hnodes[n.id] = n; });
      
      const harnessSheet = workbook.addWorksheet(hname.substring(0, 31)); // Limitar nombre de hoja
      
      // Agregar título simple (sin P/N)
      harnessSheet.addRow([hname, '', '', '', '', '', '', '']);
      harnessSheet.addRow(['', '', '', '', '', '', '', '']);
      
      // Crear lista BOM (Bill of Materials) única
      const bomList = new Map(); // Usar Map para evitar duplicados
      
      // Recopilar componentes para BOM (todos los componentes por tipo con sus P/N)
      (h.nodes || []).forEach(node => {
        const displayName = getDisplayName(node, node.id);
        const partNumber = node.pn || '';
        const type = node.type || '';
        const backshell = node.backshell || '';
        const backshellPN = node.backshellpn || '';
        
        // Agregar conector principal (siempre que tenga P/N)
        if (partNumber && partNumber.trim()) {
          const key = `${displayName}_${partNumber}`;
          if (!bomList.has(key)) {
            bomList.set(key, {
              name: displayName,
              partNumber: partNumber,
              type: type,
              quantity: 1
            });
          } else {
            // Incrementar cantidad si ya existe
            const existing = bomList.get(key);
            existing.quantity += 1;
          }
        }
        
        // Agregar backshell como fila separada (siempre que exista, con o sin P/N)
        if (backshell && backshell.trim()) {
          const backshellKey = `${backshell}_${backshellPN}`;
          if (!bomList.has(backshellKey)) {
            bomList.set(backshellKey, {
              name: backshellPN && backshellPN.trim() ? 'Backshell' : backshell,
              partNumber: backshellPN || '',
              type: 'backshell',
              quantity: 1
            });
          } else {
            // Incrementar cantidad si ya existe
            const existing = bomList.get(backshellKey);
            existing.quantity += 1;
          }
        }
      });
      
      // Agregar sección BOM
      harnessSheet.addRow(['BILL OF MATERIALS (BOM)', '', '', '', '', '', '', '']);
      harnessSheet.addRow(['']);
      harnessSheet.addRow(['Componente', 'P/N', 'Tipo', 'Cantidad']);
      
      // Agregar componentes BOM
      bomList.forEach(item => {
        harnessSheet.addRow([
          item.name,
          item.partNumber,
          item.type,
          item.quantity
        ]);
      });
      
      harnessSheet.addRow(['']);
      
      // Agregar cabeceras de conexión
      harnessSheet.addRow(['CONECTADOS', '', '', '', '', '', '', '']);
      harnessSheet.addRow(['']);
      harnessSheet.addRow(['Conector Origen', 'Pin Origen', 'Conector Destino', 'Pin Destino', 'Señal', 'Tipo Cable', 'AWG/mm2', 'Color']);
      
      // Recopilar y agregar conexiones
      const connections = [];
      (h.nodes || []).forEach(node => {
        if(node.mapping) {
          node.mapping.forEach(m => {
            if(!m.isAutoGenerated && m.targetConnectorId) {
              const targetNode = hnodes[m.targetConnectorId];
              if(targetNode) {
                connections.push({
                  originConnector: getDisplayName(node, node.id),
                  originPin: m.ownerPin || m.sourcePin || m.pin || m.originPin || '',
                  targetConnector: getDisplayName(targetNode, m.targetConnectorId),
                  targetPin: m.targetPin || '',
                  signal: m.signal || '',
                  cableType: m.cableType || '',
                  awg: formatAWGMM2(m.awg || ''),
                  color: m.iecColor || ''
                });
              }
            }
          });
        }
      });
      
      // Agregar filas de datos de conexiones
      if(connections.length > 0) {
        connections.forEach(conn => {
          harnessSheet.addRow([
            conn.originConnector,
            conn.originPin,
            conn.targetConnector,
            conn.targetPin,
            conn.signal,
            conn.cableType,
            conn.awg,
            conn.color
          ]);
        });
      } else {
        harnessSheet.addRow(['', 'No hay conexiones definidas', '', '', '', '', '', '']);
      }
      
      // Combinar celdas para el título
      harnessSheet.mergeCells('A1:H1');
      
      // Combinar celdas para títulos de secciones
      harnessSheet.mergeCells('A4:H4'); // BILL OF MATERIALS
      harnessSheet.mergeCells('A' + (bomList.size + 7) + ':H' + (bomList.size + 7)); // CONECTADOS
      
      // Aplicar formato profesional a la hoja del arnés
      applyProfessionalFormat(harnessSheet, hname);
      
      totalHarnessConnections += connections.length;
    });
    
    // Ajustar ancho de columnas para hojas de arnés (nueva estructura con BOM)
    workbook.eachSheet((worksheet) => {
      if (worksheet.name !== 'Resumen del Proyecto') {
        worksheet.getColumn(1).width = 25; // Componente/Conector Origen
        worksheet.getColumn(2).width = 15; // P/N/Pin Origen
        worksheet.getColumn(3).width = 12; // Tipo/Conector Destino
        worksheet.getColumn(4).width = 8;  // Cantidad/Pin Destino
        worksheet.getColumn(5).width = 20; // Señal
        worksheet.getColumn(6).width = 18; // Tipo Cable
        worksheet.getColumn(7).width = 10; // AWG/mm2
        worksheet.getColumn(8).width = 12; // Color
      }
    });
    
    // Generar nombre de archivo profesional
    const projectName = (AppState.project && AppState.project.meta && AppState.project.meta.projectName) || 'harnes';
    const businessUnit = (AppState.project && AppState.project.meta && AppState.project.meta.businessUnit) || 'GEN';
    const date = new Date().toISOString().split('T')[0];
    const filename = `${businessUnit}_${projectName}_${date}.xlsx`;
    
    // Escribir archivo Excel
    workbook.xlsx.writeBuffer().then(buffer => {
      const blob = new Blob([buffer], { type: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet' });
      const url = window.URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = filename;
      document.body.appendChild(a);
      a.click();
      setTimeout(() => {
        URL.revokeObjectURL(url);
        a.remove();
      }, 100);
      
      
      // Mostrar notificación de éxito
      showNotification(`Excel exportado: ${filename}`, 'success', 3000);
    });
    
  } catch(error) {
    console.error('Error al generar archivo Excel:', error);
    showNotification('Error al generar el archivo Excel: ' + error.message, 'error', 5000);
  }
});


/* ══════════════════════════════════════════════════════════════════════════
 * SECCIÓN 34: EXPORTACIÓN (Excel / CSV)
 * Generación de archivos CSV y XML compatibles con Excel a partir
 * de los datos del resumen.
 * ══════════════════════════════════════════════════════════════════════════ */
function generateExcelCompatibleCSV(data) {
  // Generar CSV delimitado por tabuladores que Excel abre sin advertencias
  let csv = '';
  
  data.forEach((row, rowIndex) => {
    // Unir las celdas con tabuladores
    const rowData = row.map(cell => {
      // Escapar tabuladores y saltos de línea
      const cellStr = String(cell || '').replace(/\t/g, ' ').replace(/\n/g, ' ').replace(/\r/g, ' ');
      // Si contiene comas o comillas, envolver en comillas y escapar comillas
      if (cellStr.includes(',') || cellStr.includes('"')) {
        return '"' + cellStr.replace(/"/g, '""') + '"';
      }
      return cellStr;
    }).join('\t');
    
    csv += rowData + '\r\n';
  });
  
  return csv;
}

function generateExcelXML(data) {
  // Mantener la función XML por si se necesita en el futuro
  // Generar contenido XML para Excel usando el estándar XML Spreadsheet 2003
  let xml = `<?xml version="1.0"?>
<?mso-application progid="Excel.Sheet"?>
<Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet"
 xmlns:o="urn:schemas-microsoft-com:office:office"
 xmlns:x="urn:schemas-microsoft-com:office:excel"
 xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"
 xmlns:html="http://www.w3.org/TR/REC-html40">
 <DocumentProperties xmlns="urn:schemas-microsoft-com:office:office">
  <Author>Harnes Designer</Author>
  <Created>${new Date().toISOString()}</Created>
  <Company>Harnes Designer</Company>
 </DocumentProperties>
 <ExcelWorkbook xmlns="urn:schemas-microsoft-com:office:excel">
  <WindowHeight>9000</WindowHeight>
  <WindowWidth>13860</WindowWidth>
  <WindowTopX>240</WindowTopX>
  <WindowTopY>75</WindowTopY>
  <ProtectStructure>False</ProtectStructure>
  <ProtectWindows>False</ProtectWindows>
 </ExcelWorkbook>
 <Styles>
  <Style ss:ID="Default" ss:Name="Normal">
   <Alignment ss:Vertical="Bottom"/>
   <Borders/>
   <Font ss:FontName="Calibri" ss:Size="11" ss:Color="#000000"/>
   <Interior/>
   <NumberFormat/>
   <Protection/>
  </Style>
  <Style ss:ID="Header">
   <Font ss:FontName="Calibri" ss:Size="11" ss:Bold="1" ss:Color="#FFFFFF"/>
   <Interior ss:Color="#4A90E2" ss:Pattern="Solid"/>
   <Alignment ss:Horizontal="Center" ss:Vertical="Center"/>
   <Borders>
    <Border ss:Position="Bottom" ss:LineStyle="Continuous" ss:Weight="1"/>
    <Border ss:Position="Left" ss:LineStyle="Continuous" ss:Weight="1"/>
    <Border ss:Position="Right" ss:LineStyle="Continuous" ss:Weight="1"/>
    <Border ss:Position="Top" ss:LineStyle="Continuous" ss:Weight="1"/>
   </Borders>
  </Style>
  <Style ss:ID="Data">
   <Font ss:FontName="Calibri" ss:Size="11" ss:Color="#000000"/>
   <Interior ss:Color="#F8F9FA" ss:Pattern="Solid"/>
   <Borders>
    <Border ss:Position="Bottom" ss:LineStyle="Continuous" ss:Weight="1"/>
    <Border ss:Position="Left" ss:LineStyle="Continuous" ss:Weight="1"/>
    <Border ss:Position="Right" ss:LineStyle="Continuous" ss:Weight="1"/>
    <Border ss:Position="Top" ss:LineStyle="Continuous" ss:Weight="1"/>
   </Borders>
  </Style>
  <Style ss:ID="AlternatingRow">
   <Font ss:FontName="Calibri" ss:Size="11" ss:Color="#000000"/>
   <Interior ss:Color="#FFFFFF" ss:Pattern="Solid"/>
   <Borders>
    <Border ss:Position="Bottom" ss:LineStyle="Continuous" ss:Weight="1"/>
    <Border ss:Position="Left" ss:LineStyle="Continuous" ss:Weight="1"/>
    <Border ss:Position="Right" ss:LineStyle="Continuous" ss:Weight="1"/>
    <Border ss:Position="Top" ss:LineStyle="Continuous" ss:Weight="1"/>
   </Borders>
  </Style>
 </Styles>
 <Worksheet ss:Name="Conexionado">
  <Table ss:ExpandedColumnCount="${data[0].length}" ss:ExpandedRowCount="${data.length}" x:FullColumns="1" x:FullRows="1" ss:DefaultRowHeight="15">`;

  data.forEach((row, rowIndex) => {
    xml += `<Row ss:Index="${rowIndex + 1}">`;
    row.forEach((cell, cellIndex) => {
      const isHeader = rowIndex === 0;
      const isAlternating = rowIndex % 2 === 0 && rowIndex > 0;
      const styleId = isHeader ? "Header" : isAlternating ? "Data" : "AlternatingRow";
      
      // Escapar caracteres especiales XML
      const escapedCell = cell.toString()
        .replace(/&/g, '&amp;')
        .replace(/</g, '&lt;')
        .replace(/>/g, '&gt;')
        .replace(/"/g, '&quot;')
        .replace(/'/g, '&#39;');
      
      xml += `<Cell ss:StyleID="${styleId}"><Data ss:Type="String">${escapedCell}</Data></Cell>`;
    });
    xml += '</Row>';
  });

  xml += `</Table>
 </Worksheet>
</Workbook>`;

  return xml;
}
