/* ╔══════════════════════════════════════════════════════════════════════════╗
 * ║  HARNESS DESIGNER — nodes.js                                               ║
 * ╠══════════════════════════════════════════════════════════════════════════╣
 * ║  Snap to grid, creación de nodos, badges, selección múltiple
 * y movimiento de nodos con arrastre.
 * ║  Secciones: 14, 15, 16, 17                                                 ║
 * ╚══════════════════════════════════════════════════════════════════════════╝
 */

/* ══════════════════════════════════════════════════════════════════════════
 * SECCIÓN 14: SNAP TO GRID Y CREACIÓN DE NODOS
 * Alineación al grid y construcción de los elementos DOM de cada nodo
 * (conector, terminal, bifurcación) con sus puertos, badges y eventos.
 * ══════════════════════════════════════════════════════════════════════════ */
function snapToGrid(tx, ty, w=NODE_W, h=NODE_H){
  const cx=tx+w/2, cy=ty+h/2;
  return { x:Math.round(cx/GRID)*GRID - w/2, y:Math.round(cy/GRID)*GRID - h/2 };
}

function createNode(type, x, y, opts={}){
  const id = 'n'+(++AppState.counters.node);
  const el = document.createElement('div');
  el.className = `node type-${type} creating`;
  el.dataset.id = id;
  el.style.left = x+'px';
  el.style.top  = y+'px';

  const bar = document.createElement('div'); bar.className='node-type-bar'; el.appendChild(bar);

  const titleEl = document.createElement('div'); titleEl.className='title';
  const name = opts.name || (type==='connector'?nextConnectorName():type==='terminal'?nextTerminalName():'Bifurcación');
  titleEl.textContent = name; el.appendChild(titleEl);

  const portsEl = document.createElement('div'); portsEl.className='ports';
  const portEl  = document.createElement('div');
  portEl.className='port'; portEl.dataset.kind='single';
  portEl.addEventListener('pointerdown', portPointerDown);
  portsEl.appendChild(portEl); el.appendChild(portsEl);

  const pnEl = document.createElement('div'); pnEl.className='pn';
  pnEl.textContent = opts.pn || ''; el.appendChild(pnEl);

  canvas.appendChild(el);

  let backshellBadge = null;
  if(type !== 'terminal'){
    backshellBadge = document.createElement('div');
    backshellBadge.className='backshell-badge';
    backshellBadge.innerHTML='<span class="bs-label">BS</span><span class="bs-text"></span>';
    canvas.appendChild(backshellBadge);
  }

  let labelBadge = null;
  // El badge de etiqueta se creará dinámicamente cuando se asigne una etiqueta

  const nodeObj = {
    el, id, type, x, y, name,
    pn: opts.pn||'',
    backshell: opts.backshell||'',
    label: opts.label||'',
    // Componentes adicionales (ej: sellos, contactos, capuchones, etc.)
    // Array<{ name: string, pn: string }>
    extraParts: Array.isArray(opts.extraParts) ? deepClone(opts.extraParts) : [],
    mapping: Array.isArray(opts.mapping) ? deepClone(opts.mapping) : [],
    connectionsCount: Number(opts.connectionsCount||(type==='terminal'?1:0)),
    backshellBadgeEl: backshellBadge,
    labelBadgeEl: labelBadge,
    harnessIndex: AppState.harness.current,
    isAutoGenerated: opts.isAutoGenerated || false
  };

  if(type==='terminal'){
    if(!Array.isArray(nodeObj.mapping)||nodeObj.mapping.length===0){
      nodeObj.mapping=[{pin:'1',targetConnectorId:'',targetPin:'',signal:'',awg:AppState.config.lastSelectedAWG}];
    } else {
      nodeObj.mapping=[Object.assign({},nodeObj.mapping[0],{pin:'1',awg:AppState.config.lastSelectedAWG})];
    }
    nodeObj.connectionsCount=1;
  }

  AppState.nodes[id] = nodeObj;
  el.addEventListener('pointerdown', nodePointerDown);
  el.addEventListener('click',   e=>{ e.stopPropagation(); selectNode(el, e.ctrlKey); });
  el.addEventListener('dblclick',e=>{ 
  e.stopPropagation(); 
  // Verificar si el doble clic viene del badge de etiqueta
  if(el._labelBadgeDblClick) {
    return; // No hacer nada, el badge ya manejó el evento
  }
  selectNode(el); 
  focusInspectorField(id,'pn'); 
});
  
  if(backshellBadge) {
    backshellBadge.addEventListener('dblclick', e => {
      e.stopPropagation();
      e.preventDefault();
      
      // Seleccionar el nodo y mostrar en el inspector
      selectNode(el);
      
      // Editar el backshell
      editBackshellBadge(AppState.nodes[id], e.clientX, e.clientY);
    });
    
    // También para depuración
    backshellBadge.addEventListener('click', e => {
    });
  }
  
  // Los eventos del badge de etiqueta se añadirán cuando se cree dinámicamente

  updateBadges(id);
  updatePortConnectedState(id);
  
  // Update connection labels table in real-time
  if (connectionLabelsTableManager) {
    connectionLabelsTableManager.updateTableForCurrentHarness();
  }
  
  // Remove creating class after animation completes
  setTimeout(() => {
    el.classList.remove('creating');
  }, 300);
  
  return id;
}


/* ══════════════════════════════════════════════════════════════════════════
 * SECCIÓN 15: BADGES (backshell y etiqueta)
 * Creación dinámica, posicionamiento y visibilidad de los badges
 * que se muestran sobre/debajo de cada nodo.
 * ══════════════════════════════════════════════════════════════════════════ */
function updateBadges(nodeId){
  const node = AppState.nodes[nodeId]; if(!node) return;
  
  if(node.backshellBadgeEl){
    const v = (node.backshell||'').trim();
    if(!v){ node.backshellBadgeEl.style.display='none'; } else {
      node.backshellBadgeEl.querySelector('.bs-text').textContent = v;
      node.backshellBadgeEl.style.display='flex';
      const canvasRect = canvas.getBoundingClientRect();
      const nodeRect   = node.el.getBoundingClientRect();
      const nx = nodeRect.left - canvasRect.left + canvas.scrollLeft;
      const ny = nodeRect.top  - canvasRect.top  + canvas.scrollTop;
      const bw = node.backshellBadgeEl.offsetWidth||90;
      node.backshellBadgeEl.style.left = Math.round(nx + NODE_W/2 - bw/2)+'px';
      node.backshellBadgeEl.style.top  = Math.round(ny + NODE_H * 1.04)+'px';
    }
  }
  
  const v = (node.label||'').trim();
  if(v && !node.labelBadgeEl){
    // Crear el badge dinámicamente con la misma estructura que el backshell
    const labelBadge = document.createElement('div');
    labelBadge.className='label-badge ' + node.type;
    labelBadge.innerHTML='<span class="lb-text"></span>';
    
    // Añadir evento de doble clic al badge con flag
    labelBadge.addEventListener('dblclick', e => {
      e.stopPropagation();
      e.preventDefault();
      
      // Marcar que el doble clic viene del badge de etiqueta
      node.el._labelBadgeDblClick = true;
      
      // Seleccionar el nodo y mostrar en el inspector
      selectNode(node.el);
      
      // Llevar al campo de etiqueta en el inspector
      focusInspectorField(node.id, 'label');
      
      // Limpiar el flag después de un tiempo
      setTimeout(() => {
        node.el._labelBadgeDblClick = false;
      }, 200);
    });
    
    // También para depuración
    labelBadge.addEventListener('click', e => {
    });
    
    // Depurar la estructura del nodo
    
    // Buscar diferentes posibles contenedores
    const badgesContainer = node.el.querySelector('.badges-container');
    const nodeContent = node.el.querySelector('.node-content');
    const directAdd = node.el;
    
    
    // Intentar añadir al badgesContainer primero
    if(badgesContainer) {
      badgesContainer.appendChild(labelBadge);
      node.labelBadgeEl = labelBadge;
    } else if(nodeContent) {
      // Si no hay badges-container, añadir a node-content
      nodeContent.appendChild(labelBadge);
      node.labelBadgeEl = labelBadge;
    } else {
      // Si no hay nada, añadir directamente al nodo
      directAdd.appendChild(labelBadge);
      node.labelBadgeEl = labelBadge;
    }
    
    // Forzar actualización inmediata con el contenido y posicionamiento correcto
    labelBadge.querySelector('.lb-text').textContent = v;
    labelBadge.style.display = 'flex';
    labelBadge.style.position = 'absolute';
    labelBadge.style.top = '-35px';
    labelBadge.style.left = '0px';
    labelBadge.style.zIndex = '10';
  }
  
  if(node.labelBadgeEl){
    if(!v){ 
      node.labelBadgeEl.style.display='none'; 
    } else {
      node.labelBadgeEl.querySelector('.lb-text').textContent = v;
      node.labelBadgeEl.style.display='flex';
      // El posicionamiento ya se estableció en la creación dinámica
    }
  }
}
function updateAllBadges(){ Object.keys(AppState.nodes).forEach(id=>updateBadges(id)); }


/* ══════════════════════════════════════════════════════════════════════════
 * SECCIÓN 16: SELECCIÓN MÚLTIPLE DE NODOS
 * Conjunto (Set) de nodos seleccionados y funciones de selección.
 * ══════════════════════════════════════════════════════════════════════════ */
// Selección múltiple mejorada con Sets para mejor rendimiento
AppState.selection.multi = new Set();
AppState.selection.isBoxSelecting = false;
AppState.selection.box = null;
AppState.selection.start = { x: 0, y: 0 };

function clearNodeSelection(){
  AppState.selection.multi.forEach(nodeId => {
    const node = AppState.nodes[nodeId];
    if(node && node.el) node.el.classList.remove('selected');
  });
  AppState.selection.multi.clear();
}

function selectNodes(nodeIds, addToSelection = false){
  if(!addToSelection) clearNodeSelection();
  nodeIds.forEach(nodeId => {
    const node = AppState.nodes[nodeId];
    if(node && node.el) {
      node.el.classList.add('selected');
      AppState.selection.multi.add(nodeId);
    }
  });
}


/* ══════════════════════════════════════════════════════════════════════════
 * SECCIÓN 17: MOVIMIENTO DE NODOS (drag)
 * Arrastre de nodos individuales o múltiples con soporte de Shift/Ctrl,
 * snap al grid y actualización de enlaces en tiempo real.
 * ══════════════════════════════════════════════════════════════════════════ */
function nodePointerDown(e){
  if(e.target.closest('.port')) return;
  e.stopPropagation();
  const nodeEl = e.currentTarget;
  const nodeId = nodeEl.dataset.id;
  
  // Manejar selección múltiple solo con Ctrl
  if(e.ctrlKey){
    selectNodes([nodeId], true);
    return;
  }
  
  // Si ya hay selección múltiple, mover todos los nodos seleccionados
  if(AppState.selection.multi.size > 1 && AppState.selection.multi.has(nodeId)){
    // Mantener la selección actual
  } else {
    // Selección normal
    clearNodeSelection();
    selectNodes([nodeId]);
  }
  
  try{ nodeEl.setPointerCapture(e.pointerId); }catch(_){}
  const canvasRect0 = canvas.getBoundingClientRect();
  const pointerStartX = e.clientX - canvasRect0.left + canvas.scrollLeft;
  const pointerStartY = e.clientY - canvasRect0.top  + canvas.scrollTop;
  const originalPositions = new Map();
  AppState.selection.multi.forEach(nid => {
    const node = AppState.nodes[nid];
    if(node) {
      originalPositions.set(nid, { x: node.x, y: node.y });
    }
  });
  let dragging = true;
  
  // Add moving class for smooth animation
  AppState.selection.multi.forEach(nid => {
    const node = AppState.nodes[nid];
    if(node) {
      node.el.classList.add('moving');
    }
  });

  function move(ev){
    if(!dragging) return;
    const cr = canvas.getBoundingClientRect();
    let currentX = ev.clientX - cr.left + canvas.scrollLeft;
    let currentY = ev.clientY - cr.top  + canvas.scrollTop;
    let deltaX = currentX - pointerStartX;
    let deltaY = currentY - pointerStartY;
    
    if(snapToggle.checked){
      const firstNodeId = Array.from(AppState.selection.multi)[0];
      const original = originalPositions.get(firstNodeId);
      if(original) {
        const snapped = snapToGrid(original.x + deltaX, original.y + deltaY);
        deltaX = snapped.x - original.x;
        deltaY = snapped.y - original.y;
      }
    }
    
    AppState.selection.multi.forEach(nid => {
      const node = AppState.nodes[nid];
      const original = originalPositions.get(nid);
      if(node && original) {
        const newX = Math.max(0, original.x + deltaX);
        const newY = Math.max(0, original.y + deltaY);
        node.el.style.left = newX + 'px'; 
        node.el.style.top = newY + 'px';
        node.x = newX; 
        node.y = newY; 
        updateLinksForNode(nid);
        updateBadges(nid);
      }
    });
  }
  
  function up(){
    try{ nodeEl.releasePointerCapture(e.pointerId); }catch(_){}
    document.removeEventListener('pointermove', move);
    document.removeEventListener('pointerup', up);
    dragging=false;
    
    // Remove moving class and add end class for smooth transition
    AppState.selection.multi.forEach(nid => {
      const node = AppState.nodes[nid];
      if(node) {
        node.el.classList.remove('moving');
        node.el.classList.add('moving.end');
        setTimeout(() => {
          node.el.classList.remove('moving.end');
        }, 200);
      }
    });
    
    markCurrentDirty();
  }
  
  document.addEventListener('pointermove', move);
  document.addEventListener('pointerup', up);
}
