/* ╔══════════════════════════════════════════════════════════════════════════╗
 * ║  HARNESS DESIGNER — serialization.js                                       ║
 * ╠══════════════════════════════════════════════════════════════════════════╣
 * ║  Serialización y restauración del estado de arneses (nodos, enlaces).      
 * ║  Secciones: 35                                                             ║
 * ╚══════════════════════════════════════════════════════════════════════════╝
 */

/* ╔══════════════════════════════════════════════════════════════════════════╗
 * ║  HARNESS DESIGNER — app.js                                                 ║
 * ╠══════════════════════════════════════════════════════════════════════════╣
 * ║  Serialización de arneses, gestión de pestañas, historial global,
 * datos de proyecto, comentarios, calendario, tabla de etiquetas e inicialización.
 * ║  Secciones: 35, 36, 37, 38, 39, 40, 41, 42                                 ║
 * ╚══════════════════════════════════════════════════════════════════════════╝
 */

/* ══════════════════════════════════════════════════════════════════════════
 * SECCIÓN 35: SERIALIZACIÓN Y ESTADO DE ARNESES
 * Funciones para convertir el estado del canvas (nodos, enlaces)
 * a objetos serializables y restaurarlos desde JSON.
 * ══════════════════════════════════════════════════════════════════════════ */
function serializeHarnessState(){
  const serializedNodes=Object.keys(AppState.nodes).map(id=>{
    const n=AppState.nodes[id];
    return {id,type:n.type,x:n.x,y:n.y,pn:n.pn||'',name:n.name||'',backshell:n.backshell||'',label:n.label||'',connectionsCount:n.connectionsCount||0,
      mapping:Array.isArray(n.mapping)?n.mapping.map(m=>({
        pin:m.pin||'',targetConnectorId:m.targetConnectorId||'',targetPin:m.targetPin||'',signal:m.signal||'',cableType:m.cableType||'',awg:m.awg||'',iecColor:m.iecColor||'',isAutoGenerated:m.isAutoGenerated||false
      })):[]};
  });
  const serializedLinks=AppState.links.map(l=>({id:l.id,fromNodeId:l.fromNodeId,toNodeId:l.toNodeId,lengthMm:l.lengthMm||'',malla:!!l.malla,termoretractil:!!l.termoretractil}));
  const serializedComments = Object.keys(AppState.comments.data).map(nodeId => ({
    nodeId,
    comments: AppState.comments.data[nodeId] || []
  }));
  const meta={exportedAt:new Date().toISOString(),name:AppState.harness.list[AppState.harness.current]?.meta?.name||`Arnés ${AppState.harness.current+1}`};
  return {nodes:serializedNodes,links:serializedLinks,comments:serializedComments,meta};
}
function serializeAllHarnesses(){
  if(AppState.harness.current>=0) saveCurrentHarnessSnapshot();
  return {project: AppState.project, harnesses:AppState.harness.list.map((h,i)=>{ const c=deepClone(h||{nodes:[],links:[],meta:{}}); if(!c.meta) c.meta={}; c.meta.name=c.meta.name||`Arnés ${i+1}`; return c; }),exportedAt:new Date().toISOString()};
}
function applyHarnessObject(obj){
  Object.keys(AppState.nodes).forEach(id=>{ const n=AppState.nodes[id]; if(n.el?.parentNode) n.el.parentNode.removeChild(n.el); if(n.backshellBadgeEl?.parentNode) n.backshellBadgeEl.parentNode.removeChild(n.backshellBadgeEl); if(n.labelBadgeEl?.parentNode) n.labelBadgeEl.parentNode.removeChild(n.labelBadgeEl); });
  AppState.nodes={}; while(svg.firstChild) svg.removeChild(svg.firstChild); AppState.links=[];
  AppState.comments.data={}; // Reset AppState.comments.data
  const idMap={};
  if(Array.isArray(obj.nodes)){
    obj.nodes.forEach(n=>{
      const cid=createNode(n.type||'connector',Number(n.x)||0,Number(n.y)||0,{
        name:n.name||undefined,
        pn:n.pn||'', 
        backshell:n.backshell||'', 
        label:n.label||'',
        mapping:n.mapping||[], 
        connectionsCount:n.connectionsCount||0,
        isAutoGenerated: n.isAutoGenerated || false
      });
      idMap[n.id]=cid;
    });
  }
  Object.keys(AppState.nodes).forEach(newId=>{
    const no=AppState.nodes[newId];
    if(!Array.isArray(no.mapping)) return;
    no.mapping=no.mapping.map(m=>({
      pin:m.pin||'',
      targetConnectorId:(m.targetConnectorId&&idMap[m.targetConnectorId])||m.targetConnectorId||'',
      targetPin:m.targetPin||'',
      signal:m.signal||'',
      cableType:m.cableType||'',
      awg:m.awg||'',
      iecColor:m.iecColor||'',
      isAutoGenerated: m.isAutoGenerated || false
    }));
  });
  if(Array.isArray(obj.links)){
    obj.links.forEach(l=>{
      const fn=idMap[l.fromNodeId], tn=idMap[l.toNodeId];
      if(fn&&tn&&AppState.nodes[fn]&&AppState.nodes[tn]){
        const cl=createLink(fn,tn,{lengthMm:l.lengthMm||'',malla:!!l.malla,termoretractil:!!l.termoretractil});
        if(cl){ cl.lengthMm=l.lengthMm||''; cl.malla=!!l.malla; cl.termoretractil=!!l.termoretractil; positionLink(cl); }
      }
    });
  }
  // Load comments
  if(Array.isArray(obj.comments)){
    obj.comments.forEach(commentGroup => {
      const newNodeId = idMap[commentGroup.nodeId] || commentGroup.nodeId;
      if(newNodeId && AppState.nodes[newNodeId]){
        AppState.comments.data[newNodeId] = commentGroup.comments || [];
      }
    });
  }
  
  // Update comment indicators for all nodes
  Object.keys(AppState.nodes).forEach(nodeId => {
    updateCommentIndicator(AppState.nodes[nodeId]);
  });
  
  let maxN=0; Object.keys(AppState.nodes).forEach(k=>{ const m=k.match(/^n(\d+)$/); if(m) maxN=Math.max(maxN,Number(m[1])); });
  AppState.counters.node=Math.max(AppState.counters.node,maxN);
  recomputeNameCounters(); redrawAll();
  // Actualizar badges para asegurar posicionamiento correcto después de cargar
  setTimeout(() => {
    updateAllBadges();
  }, 50);
}

function saveCurrentHarnessSnapshot(){
  if(AppState.harness.current<0) return;
  if(!AppState.harness.list[AppState.harness.current]) AppState.harness.list[AppState.harness.current]={nodes:[],links:[],meta:{}};
  const snap=deepClone(serializeHarnessState());
  if(!snap.meta) snap.meta={};
  snap.meta.name=AppState.harness.list[AppState.harness.current]?.meta?.name||`Arnés ${AppState.harness.current+1}`;
  // Mantener el estado dirty actual, no limpiarlo al cambiar de arnés
  snap.meta.dirty = AppState.harness.list[AppState.harness.current]?.meta?.dirty || false;
  AppState.harness.list[AppState.harness.current]=snap;
  renderTabs(); persistToLocalStorage();
}
